#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
#include "images/background.h"
#include "images/gamebackground.h"
#include "images/winscreen.h"
#include "images/planet.h"
#include "images/rocket.h"
/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};
void gameBegin(enum gba_state *);
int life = 3;

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  videoBuffer[1208] = 0x7fff;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();

    switch (state) {
      case START:
        drawFullScreenImageDMA(background);
        drawString(80,90, "WELCOME", WHITE);
        drawString(120, 50, "PRESS ENTER TO LAUNCH", WHITE);
        if(KEY_DOWN(BUTTON_START, currentButtons)) {
          state = PLAY;
        }
        break;
      case PLAY:


        // state = ?
        drawFullScreenImageDMA(gamebackground);
        gameBegin(&state);

        if(life == 0) {
          state = LOSE;
        }
        break;
      case WIN:
        drawFullScreenImageDMA(winscreen);
        drawCenteredString(0,0,WIDTH, HEIGHT, "YOU WON!", RED);
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {      //return to start screen
            life = 3;
            state = START;
        }


        // state = ?
        break;
      case LOSE:
      drawFullScreenImageDMA(winscreen);
      drawString(120,50, "OOPS LIVES OVER!", RED);
      if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {      //return to start screen
          life = 3;
          state = START;
      }
        // state = ?
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }
  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}

Rocket setUpEnemies(void) {
  Rocket r;
  r.row = 10;
  r.col = 1;
  r.w = 50;
  r.h = 30;
  drawImageDMA(r.row, r.col, r.w, r.h, rocket);
  drawImageDMA(110, 190, 50, 50, planet);
  drawRectDMA(130, 0, 40, 30, RED);
  drawRectDMA(10, 200, 40, 30, RED);
  drawString(1, 100, "lives: ", WHITE);
  if(life == 3) {
    drawString(1, 140, "3", WHITE);
  }
  if(life == 2) {
    drawString(1, 140, "2", WHITE);
  }
  if(life == 1) {
    drawString(1, 140, "1", WHITE);
  }
  if(life == 0) {
    drawString(1, 140, "0", WHITE);
  }
  return r;
}

void gameBegin(enum gba_state *state) {
  Rocket r = setUpEnemies();
  u32 currentButtons = BUTTONS;
  while (*state == PLAY) {
    waitForVBlank();
    currentButtons = BUTTONS;
    if(KEY_DOWN(BUTTON_UP, currentButtons)) {
      if(r.row > 10) {
        if((r.row >= 10 && r.row <= 50 && r.col >= 150) || (r.row >= 130 && r.col <= 40)) {
          life--;
          drawRectDMA(1, 140, 20, 20, BLACK);
          if(life == 3) {
            drawString(1, 140, "3", WHITE);
          }
          if(life == 2) {
            drawString(1, 140, "2", WHITE);
          }
          if(life == 1) {
            drawString(1, 140, "1", WHITE);
          }
          if(life == 0) {
            drawString(1, 140, "0", WHITE);
            *state = LOSE;
            return;
          }
          drawRectDMA(r.row, r.col, r.w, r.h, BLACK);
          r.row = 10;
          r.col = 1;
          r.w = 50;
          r.h = 30;
        } else {
          drawRectDMA(r.row, r.col, r.w, r.h, BLACK);
          r.row--;
        }

      }
      drawImageDMA(r.row, r.col, r.w, r.h, rocket);
      if(r.row >= 80 && r.col >= 140) {
        *state = WIN;
        return;
      }
    }
    if(KEY_DOWN(BUTTON_DOWN, currentButtons)) {
      if(r.row < 130) {
        if((r.row >= 10 && r.row <= 50 && r.col >= 150) || (r.row >= 100 && r.col <= 40)) {
          life--;
          drawRectDMA(1, 140, 20, 20, BLACK);
          if(life == 3) {
            drawString(1, 140, "3", WHITE);
          }
          if(life == 2) {
            drawString(1, 140, "2", WHITE);
          }
          if(life == 1) {
            drawString(1, 140, "1", WHITE);
          }
          if(life == 0) {
            drawString(1, 140, "0", WHITE);
            *state = LOSE;
            return;
          }
          drawRectDMA(r.row, r.col, r.w, r.h, BLACK);
          r.row = 10;
          r.col = 1;
          r.w = 50;
          r.h = 30;
        }
        else {
          drawRectDMA(r.row, r.col, r.w, r.h, BLACK);
          r.row++;
        }
      }
      drawImageDMA(r.row, r.col, r.w, r.h, rocket);
      if(r.row >= 80 && r.col >= 140) {
        *state = WIN;
        return;
      }
    }
    if(KEY_DOWN(BUTTON_RIGHT, currentButtons)) {

      if(r.col < 190) {
        if((r.row >= 10 && r.row <= 50 && r.col >= 150) || (r.row >= 130 && r.col <= 40)) {
          life--;
          drawRectDMA(1, 140, 20, 20, BLACK);
          if(life == 3) {
            drawString(1, 140, "3", WHITE);
          }
          if(life == 2) {
            drawString(1, 140, "2", WHITE);
          }
          if(life == 1) {
            drawString(1, 140, "1", WHITE);
          }
          if(life == 0) {
            drawString(1, 140, "0", WHITE);
            *state = LOSE;
            return;
          }
          drawRectDMA(r.row, r.col, r.w, r.h, BLACK);
          r.row = 10;
          r.col = 1;
          r.w = 50;
          r.h = 30;
        }
        else {
          drawRectDMA(r.row, r.col, r.w, r.h, BLACK);
          r.col++;
        }
      }
      drawImageDMA(r.row, r.col, r.w, r.h, rocket);
      if(r.row >= 80 && r.col >= 140) {
        *state = WIN;
        return;
      }
    }
    if(KEY_DOWN(BUTTON_LEFT, currentButtons)) {

       if(r.col > 0) {
         if((r.row >= 10 && r.row <= 50 && r.col >= 150) || (r.row >= 130 && r.col <= 40)) {
           life--;
           drawRectDMA(1, 140, 20, 20, BLACK);
           if(life == 3) {
             drawString(1, 140, "3", WHITE);
           }
           if(life == 2) {
             drawString(1, 140, "2", WHITE);
           }
           if(life == 1) {
             drawString(1, 140, "1", WHITE);
           }
           if(life == 0) {
             drawString(1, 140, "0", WHITE);
             *state = LOSE;
             return;
           }
           drawRectDMA(r.row, r.col, r.w, r.h, BLACK);
           r.row = 10;
           r.col = 1;
           r.w = 50;
           r.h = 30;
         }
         else {
           drawRectDMA(r.row, r.col, r.w, r.h, BLACK);
           r.col--;
         }
      }

      drawImageDMA(r.row, r.col, r.w, r.h, rocket);
      if(r.row >= 80 && r.col >= 140) {
        *state = WIN;
        return;
      }
    }
    if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {      //return to start screen
        life = 3;
        *state = START;
        return;
    }

  }

}
